os: linux
dist: xenial
services:
  - docker
language: generic
before_deploy:
  - sudo apt-get update -qy
  - sudo apt-get install -qy python3 python3-pip libyaml-dev
  - sudo python3 -m pip install packagecore
  - packagecore -o dist "${TRAVIS_TAG#v}"
deploy:
  provider: releases
  token:
    secure: 
  file_glob: true
  file:
    - dist/*
  on:
    tags: true
