sudo: required
services:
  - docker
language: python
python: '3.7'
before_install:
  - sudo apt-get install -y python3-pip
  - sudo pip3 install --upgrade pip
  - sudo pip3 install --upgrade setuptools
  - sudo pip3 install pyyaml pylint
script:
  - if [[ "${TRAVIS_TAG}" == "v${TRAVIS_TAG#v}" ]]; then [[ "${TRAVIS_TAG#v}" != "$(cat VERSION)" ]] && exit 1 || echo "Version match"; fi
  - pylint fabric-server
  - ./setup.py test
  - ./setup.py sdist
  - sudo pip3 install --upgrade "dist/fabric-server-$(cat VERSION).tar.gz"
  - if [[ "${TRAVIS_TAG}" == "v${TRAVIS_TAG#v}" ]]; then fabric-server -o /tmp -C test 1.2.3 4 || exit 1; else fabric-server -C test -o /tmp -p ubuntu20.04 1.2.3 4 || exit 1; fi
before_deploy:
  - fabric-server "${TRAVIS_TAG#v}"
deploy:
  provider: releases
  api_key:
    secure: 
  file_glob: true
  file:
    - fabric-server_*.deb
    - fabric-server-*.pkg.tar.xz
    - fabric-server-*.rpm
    - dist/fabric-server-${TRAVIS_TAG#v}.tar.gz
  skip_cleanup: true
  on:
    tags: true
